import { PipelineStage, Vendor, Lead } from './types';

export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: 'new_lead',
    label: 'Lead Nuevo',
    metaEvent: 'Lead',
    tiktokEvent: 'SubmitForm',
    color: 'border-blue-500/40 bg-blue-500/5 text-blue-400',
    accentHex: '#3b82f6',
    description: 'Instant form recibido desde Meta Ads',
  },
  {
    id: 'contacted',
    label: 'Contactado',
    metaEvent: 'Contact',
    tiktokEvent: 'Contact',
    color: 'border-sky-500/40 bg-sky-500/5 text-sky-400',
    accentHex: '#0ea5e9',
    description: 'Primer contacto vía WhatsApp o llamada telefónica',
  },
  {
    id: 'qualified',
    label: 'Calificado',
    metaEvent: 'QualifiedLead',
    tiktokEvent: 'CompleteRegistration',
    color: 'border-emerald-500/40 bg-emerald-500/5 text-emerald-400',
    accentHex: '#10b981',
    description: 'Interés confirmado y capacidad financiera verificada',
  },
  {
    id: 'visit',
    label: 'Visita Agendada',
    metaEvent: 'Schedule',
    tiktokEvent: 'Subscribe',
    color: 'border-violet-500/40 bg-violet-500/5 text-violet-400',
    accentHex: '#8b5cf6',
    description: 'Cita en terreno / showroom Olonesa Reserva confirmada',
  },
  {
    id: 'proposal',
    label: 'Propuesta Enviada',
    metaEvent: 'SubmitApplication',
    tiktokEvent: 'InitiateCheckout',
    color: 'border-amber-500/40 bg-amber-500/5 text-amber-400',
    accentHex: '#f59e0b',
    description: 'Cotización formal de lote y financiamiento 40/60 enviada',
  },
  {
    id: 'negotiation',
    label: 'Negociación',
    metaEvent: 'InitiateCheckout',
    tiktokEvent: 'AddToCart',
    color: 'border-orange-500/40 bg-orange-500/5 text-orange-400',
    accentHex: '#f97316',
    description: 'Ajuste de términos de promesa de compraventa',
  },
  {
    id: 'won',
    label: 'Venta Cerrada',
    metaEvent: 'Purchase',
    tiktokEvent: 'Purchase',
    color: 'border-emerald-400 bg-emerald-500/10 text-emerald-300',
    accentHex: '#34d399',
    description: 'Reserva pagada y contrato firmado (Optimización de máximo valor)',
    isTerminal: true,
  },
  {
    id: 'lost',
    label: 'Perdido',
    metaEvent: null,
    tiktokEvent: null,
    color: 'border-rose-500/30 bg-rose-500/5 text-rose-400',
    accentHex: '#f43f5e',
    description: 'Lead descartado (sin presupuesto o desistimiento)',
    isTerminal: true,
  },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    fullName: 'Karina Célleri',
    email: 'karina@celleri.com',
    phone: '+593 99 876 5432',
    role: 'admin',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    isActive: true,
  },
  {
    id: 'vendor-2',
    fullName: 'Roberto Mendoza',
    email: 'roberto@celleri.com',
    phone: '+593 98 765 4321',
    role: 'vendor',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isActive: true,
  },
];

export const DEMO_LEADS: Lead[] = [
  {
    id: 'lead-1',
    metaLeadId: 335286051821001,
    source: 'meta',
    fullName: 'Alejandro Valverde',
    firstName: 'Alejandro',
    lastName: 'Valverde',
    email: 'alejandro.valverde@example.com',
    phone: '+593991234567',
    city: 'Guayaquil',
    stage: 'visit',
    assignedTo: 'vendor-1',
    lotInterest: 'Lote Mirador 1,200 m²',
    budgetRange: '$180,000 - $250,000',
    dealValue: 185000,
    currency: 'USD',
    notes: 'Interesado en vista al Pacífico. Cita agendada para el sábado a las 11:00 AM.',
    campaignName: 'CAMP-OLONESA-LEADS-SEPT-V26',
    formName: 'Formulario VIP Olonesa Reserva',
    createdAt: '2026-09-11T14:30:00Z',
    updatedAt: '2026-09-12T10:15:00Z',
  },
  {
    id: 'lead-2',
    metaLeadId: 335286051821002,
    source: 'meta',
    fullName: 'María Elena Cordero',
    firstName: 'María Elena',
    lastName: 'Cordero',
    email: 'm.cordero@inversiones.ec',
    phone: '+593987654321',
    city: 'Quito',
    stage: 'proposal',
    assignedTo: 'vendor-2',
    lotInterest: 'Macrolote Privado 2,500 m²',
    budgetRange: '$300,000+',
    dealValue: 340000,
    currency: 'USD',
    notes: 'Enviada cotización con plan de financiamiento directo a 36 meses.',
    campaignName: 'CAMP-OLONESA-LEADS-SEPT-V26',
    formName: 'Formulario VIP Olonesa Reserva',
    createdAt: '2026-09-10T09:20:00Z',
    updatedAt: '2026-09-12T11:45:00Z',
  },
  {
    id: 'lead-3',
    metaLeadId: 335286051821003,
    source: 'meta',
    fullName: 'Carlos Eduardo Noboa',
    firstName: 'Carlos',
    lastName: 'Noboa',
    email: 'carlos.noboa@corp.ec',
    phone: '+593993456789',
    city: 'Samborondón',
    stage: 'qualified',
    assignedTo: 'vendor-1',
    lotInterest: 'Lote Sendero Botánico 800 m²',
    budgetRange: '$120,000 - $150,000',
    dealValue: 125000,
    currency: 'USD',
    notes: 'Llamada inicial realizada por WhatsApp. Confirma presupuesto propio.',
    campaignName: 'CAMP-OLONESA-LEADS-SEPT-V26',
    formName: 'Formulario VIP Olonesa Reserva',
    createdAt: '2026-09-12T08:10:00Z',
    updatedAt: '2026-09-12T09:30:00Z',
  },
  {
    id: 'lead-4',
    metaLeadId: 335286051821004,
    source: 'meta',
    fullName: 'Gabriela Santistevan',
    firstName: 'Gabriela',
    lastName: 'Santistevan',
    email: 'gsantistevan@studio.ec',
    phone: '+593981122334',
    city: 'Guayaquil',
    stage: 'new_lead',
    assignedTo: 'vendor-2',
    lotInterest: 'Lote Valle Sereno 1,000 m²',
    budgetRange: '$140,000 - $180,000',
    dealValue: 155000,
    currency: 'USD',
    notes: 'Ingresó hace 15 minutos vía Instagram Instant Form.',
    campaignName: 'CAMP-OLONESA-LEADS-SEPT-V26',
    formName: 'Formulario VIP Olonesa Reserva',
    createdAt: '2026-09-12T12:15:00Z',
    updatedAt: '2026-09-12T12:15:00Z',
  },
  {
    id: 'lead-5',
    metaLeadId: 335286051821005,
    source: 'meta',
    fullName: 'Dr. Fernando Alarcón',
    firstName: 'Fernando',
    lastName: 'Alarcón',
    email: 'falarcon.md@clinica.ec',
    phone: '+593995566778',
    city: 'Cuenca',
    stage: 'won',
    assignedTo: 'vendor-1',
    lotInterest: 'Lote Cumbre Master 1,500 m²',
    budgetRange: '$220,000',
    dealValue: 220000,
    currency: 'USD',
    notes: 'Promesa de compraventa firmada y reserva acreditada en fideicomiso.',
    campaignName: 'CAMP-OLONESA-LEADS-SEPT-V26',
    formName: 'Formulario VIP Olonesa Reserva',
    createdAt: '2026-09-02T16:00:00Z',
    updatedAt: '2026-09-11T18:00:00Z',
  },
];
